- name: copy files to docker master node
  ansible.builtin.copy:
    src: "{{role_path}}/files/{{ item }}"
    dest: "{{ansible_env.HOME}}/homepage"
    owner: "{{ docker_user }}"
    mode: '755'
  loop:
  - config
  - docker-compose.yml

- name: deploy homepage stack
  community.docker.docker_stack:
    name: homepage
    state: present
    compose: "{{ansible_env.HOME}}/homepage/docker-compose.yml"