- name: copy caddy configs and docker compose
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/auth/caddy/"
    owner: "{{ docker_user }}"
    mode: '655'
  loop:
  - caddy_config
  - docker-compose.yml

- name: create DOCKER volume for caddy data
  community.docker.docker_volume:
    name: caddy_data
    state: present

- name: run docker stack
  community.docker.docker_stack:
    name: auth
    state: present
    compose: "{{ ansible_env.HOME }}/auth/caddy/docker-compose.yml"
