authentication:
  hosts:
    auth:
      ansible_host:
        #Enter ip of swarm manager VM

applications:
  hosts:
    apps:
      ansible_host:
        #Enter ip of swarm worker VM

swarm_managers:
  hosts:
    auth:


swarm_workers:
  hosts:
    apps:


production:
  children:
    authentication:
    applications:
