services:
  authDB:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ${HOME}/auth/postgres/init/00-entrypoint.sh:/docker-entrypoint-initdb.d/          #uncomment if deploying first time with fresh data
    secrets:
      - authelia_db_password
      - lldap_db_password
      - postgres_password
    networks:
      - auth
    environment:
       POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    deploy:  
      labels:
        - homepage.group=Admin
        - homepage.name=authDB
        - homepage.showStats=true
      placement:
          constraints:
          - node.role == manager

networks:
  auth:
    external: true

volumes:
  pgdata:
    external: true

secrets:
  authelia_db_password:
      external: true
  lldap_db_password:
      external: true
  postgres_password:
      external: true